# Page settings

baseURL = "https://yurigabrich.github.io/"
languageCode = "en"
title = "CV Yuri Bastos Gabrich"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-158699957-16"






[params]
    author = "Yuri Bastos Gabrich"
    description = "Online CV and portfolio of an entry-level technical writer."


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Yuri Bastos Gabrich"
        tagline = "Technical Writer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Niterói (RJ)"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "https://api.whatsapp.com/send?phone=5521985000211"
        text = "+55 21 985-000-211"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:yuribgabrich@gmail.com"
        text = "yuribgabrich[at]gmail[dot]com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://github.com/yurigabrich/"
        text = "github.com/yurigabrich"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "LaTeX"
        [[params.skills.list.items]]
        details = "HTML/CSS/Markdown"
        [[params.skills.list.items]]
        details = "Python/JavaScript/C#"
        [[params.skills.list.items]]
        details = "Git/GitHub"
        [[params.skills.list.items]]
        details = "Jekyll/Hugo"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Detail-oriented"
        [[params.skills.list.items]]
        details = "Visual explainer"
        [[params.skills.list.items]]
        details = "Human-centered advocate"
        [[params.skills.list.items]]
        details = "Team facilitator"









    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Computational Science"
        university = "Rio de Janeiro State University"
        dates = "2016 - 2019"
        [[params.education.list]]
        degree = "BSc in Power Engineering"
        university = "Federal Center for Technological Education ''Celso Suckow da Fonseca''"
        dates = "2008 - 2013"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Portuguese"
        level = "Native"        
	[[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "French"
        level = "Limited"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Music"
        [[params.interests.list]]
        name = "Bike"
        [[params.interests.list]]
        name = "Adventure"
        [[params.interests.list]]
        name = "Travel"








    [params.summary]
        enable = true
        text = "With a single interest in the wise use of technology to improve people's quality of life, he believes that a multidisciplinary environment is vital to create and learn new things. He argues that documentation and design are essential to make any solution a success. This methodical and creative process is one of his passions and the excuse he uses to improve communication between various areas of knowledge."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Engineering Title Reviewer"
        dates = "Feb 2020 - Present"
        company = "Study.com"
        details = "Consultant on edit and preparation of titles and questions. Usually, performs the tasks of correcting grammar, spelling, capitalization, and punctuation errors in the original files; recreating formulas with LaTeX; organizing and re-phrasing the questions when they are poorly written; responding to feedback and requests from reviewers and updating work accordingly."

        [[params.experience.list]]
        title = "Partner Strategist"
        dates = "Sep 2017 - Dec 2019"
        company = "IEEE YP Rio de Janeiro Section"
        details = "Volunteer position to build strong relationships with organizations serving the needs of the IEEE YP Rio, and support the success of valuable events for society. By establishing and growing business and technical relationships, had the opportunity to engage with local leaders to deliver discussions about electrical vehicles, IoT and humanitarian technologies."

        [[params.experience.list]]
        title = "Chair"
        dates = "Jan 2015 - Aug 2017"
        company = "IEEE YP Rio de Janeiro Section"
        details = "Volunteer position to manage local activities on behalf of IEEE to retain graduated and professional members, and to increase the engagement of enthusiastic, dynamic, and innovative volunteers. By focusing on the presence of IEEE YP Rio on social media and other communication channels has expanded the multidisciplinary network of members that prevails until nowadays."
        [[params.experience.list.items]]
        details = "Creation of a Volunteer Manual to guide future leaders through management opportunities and pitfalls."
        [[params.experience.list.items]]
	details = "Creation of a how-to-guide for the Volunteers Mapping integration with Facebook and the updating on Google Fusion Table."

	[[params.experience.list]]
        title = "Electrical Engineering Intern"
        dates = "Aug 2012 - Mar 2013"
        company = "Cégep de Trois-Rivières (QC, Canada)"
        details = "The developer of a virtual overcurrent relay for didactic use with LabVIEW. As part of a student exchange program, has worked in collaboration with professors from both countries to design and replicate all programming menus, operating logic and device specifications."
        [[params.experience.list.items]]
        details = "Implemented a multilanguage platform ​​(Portuguese, French and English)."
        [[params.experience.list.items]]
	details = "Brang usability for specific technical configurations."
        [[params.experience.list.items]]
	details = "Created an option to generate a report in PDF of the short circuit test."
        [[params.experience.list.items]]
	details = "Failed to do the correct documentation of the software development."










    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Microgrid Transactive Energy Smart Contract"
        meta = "Open Source"
        tagline = "The beginning of a blockchain application to pave the way for Transactive Energy at Brazilian micro/mini-grids. The outcome of the master's thesis. Check out the [project page](https://yurigabrich.github.io/microgrid-dapp)."

        [[params.projects.list]]
        title = "EnergyPlus Shadow"
        meta = "Open Source"
        tagline = "A software to identify building shades surrounding a target roof during a year cycle. It borrows the codes from EnergyPlus and uses pandas to analyze a huge amont of data. Although the development has been paused for a while, contributions are welcome at the [project repo](https://github.com/yurigabrich/EnergyPlusShadow)."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2020 · Mobility, Citizens, Innovation and Technology in Digital and Smart Cities · [DOI](https://doi.org/10.3390/fi12020022)"
        [[params.information.list.items]]
        details = "2019 · When CI and Decentralized Systems Effectively Meet Smart Cities and Grids · [DOI](https://doi.org/10.1007/978-3-030-12255-3_15)"
        [[params.information.list.items]]
        details = "2017 · Tendências para Sistemas Microgrids em Cidades Inteligentes: Uma Visão Sobre a Blockchain · [PDF](http://www.sbpo2017.iltc.br/pdf/169695.pdf)"
        [[params.information.list.items]]
        details = "2010 · Energia e Meio Ambiente: uma Alternativa Sustentável - Energia Solar Fotovoltaica · [PDF](http://dippg.cefet-rj.br/attachments/article/268/PIBIC_2009_livroDeResumos.pdf)"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/yurigabrich/"
        title = ""
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/yurigabrich/"
        title = ""
        [[params.social.list]]
        icon = "fab fa-goodreads"
        url = "https://www.goodreads.com/user/show/15534139-yuri-gabrich"
        title = ""
        [[params.social.list]]
        icon = "fab fa-soundcloud"
        url = "https://soundcloud.com/yuri-gabrich"
        title = ""
        [[params.social.list]]
        icon = "fab fa-strava"
        url = "https://www.strava.com/athletes/ygabrich"
        title = ""
        [[params.social.list]]
        icon = "fas fa-passport"
        url = "https://www.couchsurfing.com/people/yuri.gabrich"
        title = ""


